import { Question } from './types';

export const KLETSEN_QUESTIONS: Question[] = [
  // MAKKELIJK (4-6 jaar)
  {
    id: 'kletsen_1',
    themeId: 'kletsen',
    level: 'makkelijk',
    type: 'open',
    text: "Stelling: Iedereen zou elke dag een ijsje moeten eten.",
    explanation: 'Wat vind jij? Is dat een goed idee of juist niet?',
    discussion: 'Waarom wel of waarom niet? En welke smaak dan?',
  },
  {
    id: 'kletsen_2',
    themeId: 'kletsen',
    level: 'makkelijk',
    type: 'open',
    text: "Stelling: Huisdieren kunnen praten als wij niet luisteren.",
    explanation: 'Zou het echt zo zijn? Wat zouden ze zeggen?',
    discussion: 'Wat zou jouw lievelingsdier tegen je zeggen?',
  },
  {
    id: 'kletsen_3',
    themeId: 'kletsen',
    level: 'makkelijk',
    type: 'open',
    text: "Stelling: Buiten spelen is leuker dan binnen spelen.",
    explanation: 'Ben je het hiermee eens?',
    discussion: 'Wat is het leukste om buiten te doen?',
  },
  {
    id: 'kletsen_4',
    themeId: 'kletsen',
    level: 'makkelijk',
    type: 'open',
    text: "Stelling: Als je groot bent, mag je alles zelf bepalen.",
    explanation: 'Is dat echt zo? Wat zou jij als eerste doen?',
    discussion: 'Wat mag je nu nog niet, maar later wel?',
  },
  {
    id: 'kletsen_5',
    themeId: 'kletsen',
    level: 'makkelijk',
    type: 'open',
    text: "Stelling: Groente eten maakt je supersterk.",
    explanation: 'Geloven we dit?',
    discussion: 'Welke groente vind jij het lekkerst?',
  },

  // MIDDEN (7-9 jaar)
  {
    id: 'kletsen_6',
    themeId: 'kletsen',
    level: 'midden',
    type: 'open',
    text: "Stelling: Kinderen zouden de baas moeten zijn op school.",
    explanation: 'Hoe zou de school er dan uitzien?',
    discussion: 'Wat is de eerste regel die je zou veranderen?',
  },
  {
    id: 'kletsen_7',
    themeId: 'kletsen',
    level: 'midden',
    type: 'open',
    text: "Stelling: Je kunt beter heel rijk zijn dan heel beroemd.",
    explanation: 'Wat kies jij?',
    discussion: 'Wat zou je doen met al dat geld of die roem?',
  },
  {
    id: 'kletsen_8',
    themeId: 'kletsen',
    level: 'midden',
    type: 'open',
    text: "Stelling: Robots gaan later al ons werk doen.",
    explanation: 'Is dat een fijne gedachte?',
    discussion: 'Welk klusje zou jij een robot laten doen?',
  },
  {
    id: 'kletsen_9',
    themeId: 'kletsen',
    level: 'midden',
    type: 'open',
    text: "Stelling: Het is belangrijker om aardig te zijn dan om te winnen.",
    explanation: 'Ben je het hiermee eens?',
    discussion: 'Kun je een voorbeeld noemen van wanneer je aardig was?',
  },
  {
    id: 'kletsen_10',
    themeId: 'kletsen',
    level: 'midden',
    type: 'open',
    text: "Stelling: Reizen naar de maan wordt over 20 jaar heel normaal.",
    explanation: 'Zou jij een ticket kopen?',
    discussion: 'Wat zou je meenemen naar de maan?',
  },

  // MOEILIJK (10-12 jaar)
  {
    id: 'kletsen_11',
    themeId: 'kletsen',
    level: 'moeilijk',
    type: 'open',
    text: "Stelling: Social media maakt mensen eenzamer.",
    explanation: 'Wat denk jij? Brengt het ons samen of juist niet?',
    discussion: 'Hoeveel tijd per dag is gezond voor social media?',
  },
  {
    id: 'kletsen_12',
    themeId: 'kletsen',
    level: 'moeilijk',
    type: 'open',
    text: "Stelling: Huiswerk moet verboden worden.",
    explanation: 'Een populaire stelling! Maar wat zijn de nadelen?',
    discussion: 'Leer je meer op school of door thuis te oefenen?',
  },
  {
    id: 'kletsen_13',
    themeId: 'kletsen',
    level: 'moeilijk',
    type: 'open',
    text: "Stelling: Je kunt alles worden wat je wilt, als je maar hard genoeg werkt.",
    explanation: 'Is dit waar, of heb je ook geluk nodig?',
    discussion: 'Wat zou jij later het allerliefst willen worden?',
  },
  {
    id: 'kletsen_14',
    themeId: 'kletsen',
    level: 'moeilijk',
    type: 'open',
    text: "Stelling: Dieren in de dierentuin zijn niet gelukkig.",
    explanation: 'Wat vind jij van dierentuinen?',
    discussion: 'Zijn er andere manieren om dieren te beschermen?',
  },
  {
    id: 'kletsen_15',
    themeId: 'kletsen',
    level: 'moeilijk',
    type: 'open',
    text: "Stelling: De wereld zou beter zijn zonder geld.",
    explanation: 'Hoe zouden we dan aan spullen komen?',
    discussion: 'Zou ruilen beter werken dan betalen?',
  },
];
